shared: &shared
  - '**'
  - '!platform/*/**'
  - '!doc/**'
# GitHub Actions
  - '!.github/workflows/**'
  - '.github/workflows/runner.yml'
  - '.github/workflows/static_checks.yml'
# Static File Types
  - '!**/*.md'
  - '!**/*.png'
android:
  - *shared
  - 'platform/android/**'
  - '.github/workflows/android_builds.yml'
  - '!tests/**'
ios:
  - *shared
  - 'platform/ios/**'
  - '.github/workflows/ios_builds.yml'
  - '!tests/**'
linux:
  - *shared
  - 'platform/linuxbsd/**'
  - '.github/workflows/linux_builds.yml'
  - '.github/workflows/godot_cpp_test.yml'
# Docs are checked in one workflow here.
  - 'doc/**'
macos:
  - *shared
  - 'platform/macos/**'
  - '.github/workflows/macos_builds.yml'
windows:
  - *shared
  - 'platform/windows/**'
  - '.github/workflows/windows_builds.yml'
web:
  - *shared
  - 'platform/web/**'
  - '.github/workflows/web_builds.yml'
  - '!tests/**'
